### ISSUE TITLE
import is broken

### ISSUE THREAD

**Issue by patel-zeel** [deepmind/distrax#145]
Hi,

I am getting the following error after installing the latest version of JAX v0.3.7 on Google colaboratory as well as my local system Ubuntu 20.04.
```py
import distrax
```
Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/patel_zeel/miniconda3/envs/pyprobml/lib/python3.9/site-packages/distrax/__init__.py", line 20, in <module>
    from distrax._src.bijectors.block import Block
  File "/home/patel_zeel/miniconda3/envs/pyprobml/lib/python3.9/site-packages/distrax/_src/bijectors/block.py", line 20, in <module>
    from distrax._src.utils import conversion
  File "/home/patel_zeel/miniconda3/envs/pyprobml/lib/python3.9/site-packages/distrax/_src/utils/conversion.py", line 19, in <module>
    import chex
  File "/home/patel_zeel/miniconda3/envs/pyprobml/lib/python3.9/site-packages/chex/__init__.py", line 17, in <module>
    from chex._src.asserts import assert_axis_dimension
  File "/home/patel_zeel/miniconda3/envs/pyprobml/lib/python3.9/site-packages/chex/_src/asserts.py", line 26, in <module>
    from chex._src import asserts_internal as _ai
  File "/home/patel_zeel/miniconda3/envs/pyprobml/lib/python3.9/site-packages/chex/_src/asserts_internal.py", line 32, in <module>
    from chex._src import pytypes
  File "/home/patel_zeel/miniconda3/envs/pyprobml/lib/python3.9/site-packages/chex/_src/pytypes.py", line 40, in <module>
    CpuDevice = jax.lib.xla_extension.CpuDevice
AttributeError: module 'jaxlib.xla_extension' has no attribute 'CpuDevice'
```
<img width="725" alt="image" src="https://user-images.githubusercontent.com/59758528/163733013-12dfce74-4444-4caf-8f64-6ac0f358aa8d.png">

**Comment by gpapamak** [comment]
This seems to be due to an underlying issue with `chex`, which is imported by `distrax`:

https://github.com/deepmind/chex/issues/156

cc @hbq1

**Comment by hbq1** [comment]
It was fixed in [chex v0.1.3](https://github.com/deepmind/chex/releases/tag/v0.1.3), thanks!

**Comment by patel-zeel** [comment]
It is working now! Our workflows are happy :) Thank you @hbq1 and @gpapamak.
