### ISSUE TITLE
`distrax.Distribution` leak state when used with `jax.lax.scan`/`hk.dynamic_unroll`

### ISSUE THREAD

**Issue by filangelos** [deepmind/distrax#64]
While I was trying to build a `hk.RNNCore` with a state that contains a `distrax.Distribution` I noticed that when the core was **not** compatible with `hk.dynamic_unroll`, leading to a leakage error.

I am providing an example code snippet below.

```python
from typing import NamedTuple, Optional, Tuple

import chex
import distrax
import haiku as hk
import jax
import jax.numpy as jnp


class DistribRNNState(NamedTuple):
  """Container for holding the `DistribRNN`'s state."""
  sample: chex.Array
  loc: chex.Array
  scale_diag: chex.Array
  distrib: distrax.MultivariateNormalDiag

  @classmethod
  def from_flat_vector(
      cls,
      flat_vector: chex.Array,
      *,
      rng_key: chex.PRNGKey,
  ) -> "DistribRNNState":
    """Split the `flat_vector` to `loc` and `scale_diag`, transform
    `scale_diag` and get a sample from the MVN distribution."""
    loc, scale_diag = jnp.split(flat_vector, indices_or_sections=2, axis=-1)
    scale_diag = jax.nn.softplus(scale_diag)
    distrib = distrax.MultivariateNormalDiag(loc=loc, scale_diag=scale_diag)
    sample = distrib.sample(seed=rng_key)
    return cls(sample=sample, loc=loc, scale_diag=scale_diag, distrib=distrib)


class DistribRNN(hk.RNNCore):
  """A simple RNN that parametrises a MVN distribution."""

  def __init__(self, hidden_size: int, name: Optional[str] = None) -> None:
    """Construct a multivariate normal distribution recurrent core."""
    super().__init__(name=name)

    # Internalise passed arguments.
    self._hidden_size = hidden_size

    # The multi-layer-perceptron used for the dynamics.
    self._mlp = hk.nets.MLP(
        output_sizes=(self._hidden_size * 2, self._hidden_size * 2),
        activate_final=False)

  def initial_state(self, batch_size: int) -> DistribRNNState:
    """Return the (untrainable) initial state."""
    assert batch_size is not None
    loc = jnp.zeros(shape=(batch_size, self._hidden_size))
    scale_diag = jnp.ones(shape=(batch_size, self._hidden_size))
    distrib = distrax.MultivariateNormalDiag(loc=loc, scale_diag=scale_diag)
    return DistribRNNState(
        sample=loc, loc=loc, scale_diag=scale_diag, distrib=distrib)

  def __call__(
      self,
      inputs: chex.Array,
      prev_state: DistribRNNState,
  ) -> Tuple[chex.Array, DistribRNNState]:
    """Return the next (belief) state after observing `inputs`."""
    if len(inputs.shape) > 2 or not inputs.shape:
      raise ValueError("DistribRNN input must be rank-1 or rank-2.")
    x_and_h = jnp.concatenate([inputs, prev_state.sample], axis=-1)
    core_output = self._mlp(x_and_h)
    state = DistribRNNState.from_flat_vector(
        core_output, rng_key=hk.next_rng_key())
    return state.sample, state


rnn_hidden_size = 7
batch_size = 9
input_size = 8
rng_key = jax.random.PRNGKey(42)
core_factory = lambda: DistribRNN(hidden_size=rnn_hidden_size)
inputs = jnp.zeros(shape=(batch_size, input_size))

core = hk.transform(lambda x, h: core_factory()(x, h))
state = hk.transform(lambda b: core_factory().initial_state(b)).apply(
    {}, rng_key, batch_size)
params = core.init(rng_key, inputs, state)
output, new_state = core.apply(params, rng_key, inputs, state)
# One-step WORKS.
print(jax.tree_map(jnp.shape, (output, state, new_state)))
# => ((9, 7), DistribRNNState(sample=(9, 7), loc=(9, 7), scale_diag=(9, 7), distrib=<distrax._src.distributions.mvn_diag.MultivariateNormalDiag object at 0x7f51300f1d50>), DistribRNNState(sample=(9, 7), loc=(9, 7), scale_diag=(9, 7), distrib=<distrax._src.distributions.mvn_diag.MultivariateNormalDiag object at 0x7f51300f1310>))

@hk.transform
def unroll(inputs, prev_state):
  return hk.dynamic_unroll(core_factory(), inputs, prev_state)


T_inputs = jnp.expand_dims(inputs, axis=0)
params = unroll.init(rng_key, T_inputs, state)
output, new_state = unroll.apply(params, rng_key, T_inputs, state)
# `jax.lax.scan` does **not** work with `distrax.Distribution`s.
print(jax.tree_map(jnp.shape, (output, state, new_state)))
```

Leading to an error message:
```bash
Traceback (most recent call last):
  File "tmp/distrax_jittable_issue.py", line 95, in <module>
    output, new_state = unroll.apply(params, rng_key, T_inputs, state)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/haiku/_src/transform.py", line 127, in apply_fn
    out, state = f.apply(params, {}, *args, **kwargs)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/haiku/_src/transform.py", line 383, in apply_fn
    out = f(*args, **kwargs)
  File "tmp/distrax_jittable_issue.py", line 90, in unroll
    return hk.dynamic_unroll(core_factory(), inputs, prev_state)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/haiku/_src/recurrent.py", line 192, in dynamic_unroll
    reverse=reverse)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/haiku/_src/stateful.py", line 509, in scan
    stateful_fun, init, xs, length, reverse, unroll=unroll)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/jax/_src/lax/control_flow.py", line 1332, in scan
    init_tree, carry_avals)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/jax/_src/lax/control_flow.py", line 1984, in _check_tree_and_avals
    if tree1 != tree2:
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/jax/core.py", line 504, in __eq__
    def __eq__(self, other): return self.aval._eq(self, other)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 6553, in deferring_binary_op
    return binary_op(self, other)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/jax/_src/api.py", line 414, in cache_miss
    donated_invars=donated_invars, inline=inline)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/jax/core.py", line 1618, in bind
    return call_bind(self, fun, *args, **params)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/jax/core.py", line 1604, in call_bind
    top_trace = find_top_trace(args)
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/jax/core.py", line 859, in find_top_trace
    top_tracer._assert_live()
  File "/scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1153, in _assert_live
    raise core.escaped_tracer_error(self, None)
jax._src.traceback_util.UnfilteredStackTrace: jax._src.errors.UnexpectedTracerError: Encountered an unexpected tracer. A function transformed by JAX had a side effect, allowing for a reference to an intermediate value with shape (9, 7) and dtype float32 to escape.
JAX transformations require that functions explicitly return their outputs, and disallow saving intermediate values to global state.
The function being traced when the value leaked was scan_f at /scratch/anglos/conda_envs/markov/lib/python3.7/site-packages/haiku/_src/recurrent.py:182 traced for scan.
```

Note that passing only the `loc` and `scale_diag` (distribution) parameters works fine (as expected):

```python
from typing import NamedTuple, Optional, Tuple

import chex
import distrax
import haiku as hk
import jax
import jax.numpy as jnp


class DistribRNNState(NamedTuple):
  """Container for holding the `DistribRNN`'s state."""
  sample: chex.Array
  loc: chex.Array
  scale_diag: chex.Array
  # distrib: distrax.MultivariateNormalDiag

  @classmethod
  def from_flat_vector(
      cls,
      flat_vector: chex.Array,
      *,
      rng_key: chex.PRNGKey,
  ) -> "DistribRNNState":
    """Split the `flat_vector` to `loc` and `scale_diag`, transform
    `scale_diag` and get a sample from the MVN distribution."""
    loc, scale_diag = jnp.split(flat_vector, indices_or_sections=2, axis=-1)
    scale_diag = jax.nn.softplus(scale_diag)
    distrib = distrax.MultivariateNormalDiag(loc=loc, scale_diag=scale_diag)
    sample = distrib.sample(seed=rng_key)
    # return cls(sample=sample, loc=loc, scale_diag=scale_diag, distrib=distrib)
    return cls(sample=sample, loc=loc, scale_diag=scale_diag)


class DistribRNN(hk.RNNCore):
  """A simple RNN that parametrises a MVN distribution."""

  def __init__(self, hidden_size: int, name: Optional[str] = None) -> None:
    """Construct a multivariate normal distribution recurrent core."""
    super().__init__(name=name)

    # Internalise passed arguments.
    self._hidden_size = hidden_size

    # The multi-layer-perceptron used for the dynamics.
    self._mlp = hk.nets.MLP(
        output_sizes=(self._hidden_size * 2, self._hidden_size * 2),
        activate_final=False)

  def initial_state(self, batch_size: int) -> DistribRNNState:
    """Return the (untrainable) initial state."""
    assert batch_size is not None
    loc = jnp.zeros(shape=(batch_size, self._hidden_size))
    scale_diag = jnp.ones(shape=(batch_size, self._hidden_size))
    distrib = distrax.MultivariateNormalDiag(loc=loc, scale_diag=scale_diag)
    # return DistribRNNState(
    #     sample=loc, loc=loc, scale_diag=scale_diag, distrib=distrib)
    return DistribRNNState(sample=loc, loc=loc, scale_diag=scale_diag)

  def __call__(
      self,
      inputs: chex.Array,
      prev_state: DistribRNNState,
  ) -> Tuple[chex.Array, DistribRNNState]:
    """Return the next (belief) state after observing `inputs`."""
    if len(inputs.shape) > 2 or not inputs.shape:
      raise ValueError("DistribRNN input must be rank-1 or rank-2.")
    x_and_h = jnp.concatenate([inputs, prev_state.sample], axis=-1)
    core_output = self._mlp(x_and_h)
    state = DistribRNNState.from_flat_vector(
        core_output, rng_key=hk.next_rng_key())
    return state.sample, state


rnn_hidden_size = 7
batch_size = 9
input_size = 8
rng_key = jax.random.PRNGKey(42)
core_factory = lambda: DistribRNN(hidden_size=rnn_hidden_size)
inputs = jnp.zeros(shape=(batch_size, input_size))

core = hk.transform(lambda x, h: core_factory()(x, h))
state = hk.transform(lambda b: core_factory().initial_state(b)).apply(
    {}, rng_key, batch_size)
params = core.init(rng_key, inputs, state)
output, new_state = core.apply(params, rng_key, inputs, state)
# One-step WORKS.
print(jax.tree_map(jnp.shape, (output, state, new_state)))
# => ((9, 7), DistribRNNState(sample=(9, 7), loc=(9, 7), scale_diag=(9, 7)), DistribRNNState(sample=(9, 7), loc=(9, 7), scale_diag=(9, 7)))

@hk.transform
def unroll(inputs, prev_state):
  return hk.dynamic_unroll(core_factory(), inputs, prev_state)


T_inputs = jnp.expand_dims(inputs, axis=0)
params = unroll.init(rng_key, T_inputs, state)
output, new_state = unroll.apply(params, rng_key, T_inputs, state)
# Multi-step WORKS.
print(jax.tree_map(jnp.shape, (output, state, new_state)))
# => ((1, 9, 7), DistribRNNState(sample=(9, 7), loc=(9, 7), scale_diag=(9, 7)), DistribRNNState(sample=(9, 7), loc=(9, 7), scale_diag=(9, 7)))
```

**Comment by tomhennigan** [comment]
Hi @filangelos, thank you for the reproducer. The core issue here is the way that distrax `@Jittable` types (such as `MultivariateNormalDiag`) are registered as pytrees with no leaves, to enable this they "close over" their constructor args/kwargs. If you construct one inside a scan and return it, the values you close over will be tracers, leading to this tracer error.

Here is a minimal example that does not involve Haiku (note that `hk.dynamic_unroll` lowers to `scan` so this is roughly equivalent to the error you are seeing):

```python
import jax
import jax.numpy as jnp
import distrax

c, x = jax.lax.scan(
    lambda c, x: (None, distrax.MultivariateNormalDiag(loc=x, scale_diag=x)),
    None, jnp.zeros([1, 1]))

x.sample(seed=3)  # UnexpectedTracerError
```

One potential solution is to not return the object instance, but instead return (for example) the loc and scale params from the scanned function. You could alternatively implement your own pytree wrapper that would not close over the constructor arguments. The following seems to work for me:

```python
import jax
import jax.numpy as jnp
import distrax

@jax.tree_util.register_pytree_node_class
class DistraxReturner:
  def __init__(self, d):
    self.d = d

  def tree_flatten(self):
    leaves, treedef = jax.tree_flatten((self.d._args, self.d._kwargs),
                                       is_leaf=lambda x: isinstance(x, jnp.ndarray))
    cls = type(self.d)
    return leaves, (cls, treedef)

  @classmethod
  def tree_unflatten(cls, aux, leaves):
    cls, treedef = aux
    args, kwargs = jax.tree_unflatten(treedef, leaves)
    return cls(*args, **kwargs)

c, x = jax.lax.scan(
    lambda c, x: (None, DistraxReturner(distrax.MultivariateNormalDiag(loc=x, scale_diag=x))),
    None, jnp.zeros([1, 1]))

x.sample(seed=3)
```

Another solution that may or may not be appropriate would be to use `hk.static_unroll` which does not use `scan`.

**Comment by filangelos** [comment]
Thanks, @tomhennigan! I ended up using `hk.static_unroll`! I am closing the issue 👍
